export default {
  results: [
    {
      'ykd_teacher-id': 1,
      'ykd_teacher-name': '不知火舞',
      'ykd_teacher-gmt_created': null,
      'ykd_teacher-gmt_modified': null,
      'ykd_course-id': null,
      'ykd_course-name': null,
      'ykd_course-teacher_id': null,
      'ykd_course-gmt_created': null,
      'ykd_course-gmt_modified': null,
    },
    {
      'ykd_teacher-id': 2,
      'ykd_teacher-name': '兰陵王',
      'ykd_teacher-gmt_created': null,
      'ykd_teacher-gmt_modified': null,
      'ykd_course-id': null,
      'ykd_course-name': null,
      'ykd_course-teacher_id': null,
      'ykd_course-gmt_created': null,
      'ykd_course-gmt_modified': null,
    },
    {
      'ykd_teacher-id': 3,
      'ykd_teacher-name': '王昭君',
      'ykd_teacher-gmt_created': null,
      'ykd_teacher-gmt_modified': null,
      'ykd_course-id': null,
      'ykd_course-name': null,
      'ykd_course-teacher_id': null,
      'ykd_course-gmt_created': null,
      'ykd_course-gmt_modified': null,
    },
    {
      'ykd_teacher-id': 4,
      'ykd_teacher-name': '蔡文姬',
      'ykd_teacher-gmt_created': null,
      'ykd_teacher-gmt_modified': null,
      'ykd_course-id': null,
      'ykd_course-name': null,
      'ykd_course-teacher_id': null,
      'ykd_course-gmt_created': null,
      'ykd_course-gmt_modified': null,
    },
  ],
  fields: [
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_teacher',
      orgTable: 'ykd_teacher',
      name: 'id',
      orgName: 'id',
      charsetNr: 63,
      length: 10,
      type: 3,
      flags: 20483,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_teacher',
      orgTable: 'ykd_teacher',
      name: 'name',
      orgName: 'name',
      charsetNr: 33,
      length: 30,
      type: 253,
      flags: 4097,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_teacher',
      orgTable: 'ykd_teacher',
      name: 'gmt_created',
      orgName: 'gmt_created',
      charsetNr: 63,
      length: 19,
      type: 12,
      flags: 128,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_teacher',
      orgTable: 'ykd_teacher',
      name: 'gmt_modified',
      orgName: 'gmt_modified',
      charsetNr: 63,
      length: 19,
      type: 12,
      flags: 128,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_course',
      orgTable: 'ykd_course',
      name: 'id',
      orgName: 'id',
      charsetNr: 63,
      length: 10,
      type: 3,
      flags: 20482,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_course',
      orgTable: 'ykd_course',
      name: 'name',
      orgName: 'name',
      charsetNr: 33,
      length: 30,
      type: 253,
      flags: 4096,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_course',
      orgTable: 'ykd_course',
      name: 'teacher_id',
      orgName: 'teacher_id',
      charsetNr: 63,
      length: 10,
      type: 3,
      flags: 4096,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_course',
      orgTable: 'ykd_course',
      name: 'gmt_created',
      orgName: 'gmt_created',
      charsetNr: 63,
      length: 19,
      type: 12,
      flags: 128,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_course',
      orgTable: 'ykd_course',
      name: 'gmt_modified',
      orgName: 'gmt_modified',
      charsetNr: 63,
      length: 19,
      type: 12,
      flags: 128,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
  ],
};
