export default {
  results: [
    {
      test: 'test',
    },
  ],
  fields: [
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'timi_adc',
      orgTable: 'timi_adc',
      name: 'hero_name',
      orgName: 'hero_name',
      charsetNr: 33,
      length: 60,
      type: 253,
      flags: 4097,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'timi_adc',
      orgTable: 'timi_adc',
      name: 'id',
      orgName: 'id',
      charsetNr: 63,
      length: 10,
      type: 3,
      flags: 20483,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'timi_adc',
      orgTable: 'timi_adc',
      name: 'fever',
      orgName: 'fever',
      charsetNr: 33,
      length: 30,
      type: 253,
      flags: 4097,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
  ],
};
