export default {
  results: [
    {
      _id: 'CLOTHING',
      names: [
        '杰克琼斯运动寸衫',
        '海澜之家夏季最新款寸衫',
        '夏季气质碎花裙子夏装',
      ],
    },
    {
      _id: 'SHOE',
      names: ['安踏最新运动款跑步鞋', '亚瑟士最新款运动鞋', '新伯伦最新运动鞋'],
    },
  ],
  fields: [
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_teacher',
      orgTable: 'ykd_teacher',
      name: 'id',
      orgName: 'id',
      charsetNr: 63,
      length: 10,
      type: 3,
      flags: 20483,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_teacher',
      orgTable: 'ykd_teacher',
      name: 'name',
      orgName: 'name',
      charsetNr: 33,
      length: 30,
      type: 253,
      flags: 4097,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_teacher',
      orgTable: 'ykd_teacher',
      name: 'gmt_created',
      orgName: 'gmt_created',
      charsetNr: 63,
      length: 19,
      type: 12,
      flags: 128,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'ykd_teacher',
      orgTable: 'ykd_teacher',
      name: 'gmt_modified',
      orgName: 'gmt_modified',
      charsetNr: 63,
      length: 19,
      type: 12,
      flags: 128,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
  ],
};
