export default {
  results: [
    { hero_name: '鲁班七号', win_rate: 0.5062 },
    { hero_name: '狄仁杰', win_rate: 0.5082 },
    { hero_name: '虞姬', win_rate: 0.5111 },
    { hero_name: '伽罗', win_rate: 0.5261 },
    { hero_name: '成吉思汗', win_rate: 0.5251 },
    { hero_name: '黄忠', win_rate: 0.515 },
  ],
  fields: [
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'timi_adc',
      orgTable: 'timi_adc',
      name: 'hero_name',
      orgName: 'hero_name',
      charsetNr: 33,
      length: 60,
      type: 253,
      flags: 4097,
      decimals: 0,
      zeroFill: false,
      protocol41: true,
    },
    {
      catalog: 'def',
      db: 'yebingdb',
      table: 'timi_adc',
      orgTable: 'timi_adc',
      name: 'win_rate',
      orgName: 'win_rate',
      charsetNr: 63,
      length: 22,
      type: 5,
      flags: 4097,
      decimals: 31,
      zeroFill: false,
      protocol41: true,
    },
  ],
};
